# Local Development Secrets Template
# Copy this to .streamlit/secrets.toml for local testing
# Make sure .streamlit/secrets.toml is in your .gitignore

GROQ_API_KEY = "gsk_your_actual_groq_api_key_here"
GOOGLE_API_KEY = "your_actual_google_api_key_here"
OPENROUTER_API_KEY = "sk-or-v1-your_actual_openrouter_api_key_here"

SECRET_KEY = "your_local_development_secret_key"
DATA_ENCRYPTION_KEY = "your_local_development_encryption_key"
ALLOWED_HOSTS = "localhost,127.0.0.1"
UPLOAD_MAX_SIZE_MB = "10"
API_RATE_LIMIT_PER_MINUTE = "60"
USER_QUERY_LIMIT_PER_HOUR = "100"

ENVIRONMENT = "development"
LOG_LEVEL = "DEBUG"
DEBUG_MODE = "true"

STUDY_NAME = "LLM Business Intelligence Comparison - Dev"
CONSENT_VERSION = "1.0"
IRB_APPROVAL = "true" 