# Copy this content to Streamlit Cloud Secrets Management
# Go to: Your Streamlit App → Settings → Secrets
# Paste this content and replace placeholder values with your actual API keys

GROQ_API_KEY = "gsk_your_actual_groq_api_key_here"
GOOGLE_API_KEY = "your_actual_google_api_key_here"
OPENROUTER_API_KEY = "sk-or-v1-your_actual_openrouter_api_key_here"

SECRET_KEY = "your_random_secret_key_here"
DATA_ENCRYPTION_KEY = "your_random_encryption_key_here"
ALLOWED_HOSTS = "localhost,127.0.0.1"
UPLOAD_MAX_SIZE_MB = "10"
API_RATE_LIMIT_PER_MINUTE = "60"
USER_QUERY_LIMIT_PER_HOUR = "100"

ENVIRONMENT = "production"
LOG_LEVEL = "INFO"
DEBUG_MODE = "false"

STUDY_NAME = "LLM Business Intelligence Comparison"
CONSENT_VERSION = "1.0"
IRB_APPROVAL = "true" 