- provider: groq
  name: llama3-8b-8192
  family: llama3
  base_model: meta-llama
  token_limit: 8192
  speed_category: fast
  tags: [fastest]
- provider: groq
  name: llama-3.1-8b-instant
  family: llama3
  base_model: meta-llama
  token_limit: 8192
  speed_category: fast
  tags: [fastest]
- provider: groq
  name: qwen-qwq-32b
  family: qwen
  base_model: qwen
  token_limit: 32768
  speed_category: medium
  tags: []
- provider: gemini
  name: gemini-pro
  family: gemini
  base_model: gemini-pro
  token_limit: 8192
  speed_category: medium
  tags: [most accurate]
- provider: gemini
  name: gemini-1.5-flash
  family: gemini
  base_model: gemini-1.5-flash
  token_limit: 32768
  speed_category: fast
  tags: [fastest]
- provider: openrouter
  name: openai/gpt-3.5-turbo
  family: gpt-3.5
  base_model: gpt-3.5-turbo
  token_limit: 4096
  speed_category: fast
  tags: [most concise]
- provider: openrouter
  name: openai/gpt-4-turbo
  family: gpt-4
  base_model: gpt-4-turbo
  token_limit: 128000
  speed_category: slow
  tags: [most accurate] 